obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_board_data.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_layout_data.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_plat_data.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_plat_clanton_hill.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_plat_clanton_peak.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_plat_cross_hill.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_plat_kips_bay.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_plat_izmir.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_sb.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_imr.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_imr_kernel.o
obj-$(CONFIG_INTEL_CLN_ESRAM)	+= intel_cln_esram.o
obj-$(CONFIG_INTEL_CLN_SOC)	+= intel_cln_imr_test.o
obj-$(CONFIG_INTEL_CLN_ESRAM)	+= intel_cln_esram_test.o
#obj-$(CONFIG_INTEL_CLN_ESRAM)	+= intel_cln_smep_test.o

